language: node_js
node_js:
- 5.6
cache:
  directories:
  - node_modules
  - typings
deploy:
  provider: npm
  email: dave@etianen.com
  api_key:
    secure: "o8xYB7pmWK8KktVg3ujG0sWCBBFcVJO15+uO944BrZqbNLGNKO2eB2tJDA7cW7CuOV80/w7yTjZyewbuY+RNxy+vxAmEq380eUZQ1WMweK2oyQFf3O2iVGdJHbR7akHj82InA4M9FcF/2xJU0ZPDaDodwb9DrdkLeSa1g4U9OMG8NbsfpbR+Ys4Qc+WzEvLQgk20wQpW8S1353kkdxuD3I8iAmztjGQWx4XVe2xKDEHBxHfKfHnSJny46t8yPAQlq6zDNf6VoBDSg23Z0dorgfBWsZYJ7ZtzN++lQ1xEUOBGNiFAIiD32C8Z0PG5imJhvz7G20S4H+0aEooExkRkLI0qIRZ5Y+3WhER7AhQfcvdqFdv1lkwUi53rteTxymDej5lKwnPARe/16pIjK2fYHkFH5EwvFYIfg0MuO642GuYxliyRHbtw6I3nWeI02G3YitYl4iZwDYwjN03U2gMS4pRqnnyuuWZxDJN6McD6oAwPk9rX/1t5ktGqG98dAAG5Zo2uQ05g64Zlv+1ex4RyUZ1KGz+iHi4CDnpCLiMRAx+g0Lr9FLvU7nJw8d7S5nyxVoPHZwUQf5rPA7y7i7aVarxa1TAxpi1CAx10thF6HLl24cdAiurcS6SAFv2AkSCNhLdFbwtqoXw2hblsebxRF/aJXsjYVBGu+BcVurqwCJQ="
  skip_cleanup: true
  on:
    tags: true
    repo: etianen/js-set
notifications:
  on_success: never
  on_failure: change
