language: node_js
node_js:
- 5.6
cache:
  directories:
  - node_modules
  - typings
deploy:
  provider: npm
  email: dave@etianen.com
  api_key:
    secure: "b/zVABVlDdmtO9vjRvJaiyOYG1fh++L04V4pugOjghA+X2prH4IGpJBrlJnPyuCzS/Ui/FUEq9Bz0uq5UYvA2Z+RPinDgEkXCCY5m/pXp6O5HBAsdpxLhxfwo8L5C6XgyiUmnD5umFcbXgmOv83wJDDIp2ppMMgZoRP4El4BvhtgmLioC75xoqmv0yIjqtN4SsI9JQDTykVAk2I0e9zgd0vF5Yfx6l3xO48/tyg1r7N+MFala7AIyN8lJ6Nwd5K833AkHZvxX2WNaZWwjonAgh5q0JMqt4PttdUsa9JFKdedOHWm9wT4F99e2bXM30O62hEsPc1/aRvzog+Xf8+jtnp5XfnvoN6w8MuRN0YTM4ZPTYf9yN7L4ftm0dfEPQaIM6hiWMci2df7xxu/UFR1xBsUbrGy9lLEKkDlrQQDLqutdOC76bBsGk9wbDpHDfIOkjKDgXjb0sSxoM9aM7fk6JGk4ZjXw21ejFnFinscHGGH7hgg71hLJ252j/lA//eJXApq3QxPfDjac7B601aTXIFfksXI+qppVvXEvD5q+cssp3n0StVS2gZP/YTgzBkkCBMQWKL+nAhm7qIfg6BxsmoT8rkVMPCqZxMlwPecq3xBi8bByd0gLMKmxFJMfDot11+Pnm8XoShzmEvSJEJC8kKthSPom8U3War7n8qPStE="
  skip_cleanup: true
  on:
    tags: true
    repo: etianen/js-set
notifications:
  on_success: never
  on_failure: change
